# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/audio/remote/BoardConfig.mk
##############################################################
# Use XML audio policy configuration file
USE_XML_AUDIO_POLICY_CONF ?= 1
##############################################################
# Source: device/intel/mixins/groups/device-specific/cic-cloud/BoardConfig.mk
##############################################################
# define cic_cloud overlay
DEVICE_PACKAGE_OVERLAYS += ${TARGET_DEVICE_DIR}/extra_files/device-specific/overlay

DEVICE_MANIFEST_FILE := ${TARGET_DEVICE_DIR}/manifest.xml

BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true

# The generic product target doesn't have any hardware-specific pieces.
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_CPU_ABI := x86_64
TARGET_ARCH := x86_64
TARGET_ARCH_VARIANT := x86_64
TARGET_PRELINK_MODULE := false

TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := x86

TARGET_USES_64_BIT_BINDER := true

# Enable dex-preoptimization to speed up the first boot sequence
# of an SDK AVD. Note that this operation only works on Linux for now
ifeq ($(HOST_OS),linux)
WITH_DEXPREOPT ?= true
endif

# Container related configurations
ANDROID_AS_GUEST := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE :=   3758096384  # 3.5 GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 576716800
BOARD_CACHEIMAGE_PARTITION_SIZE := 69206016
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
DEVICE_MATRIX_FILE   := ${TARGET_DEVICE_DIR}/compatibility_matrix.xml
##############################################################
# Source: device/intel/mixins/groups/graphics/true/BoardConfig.mk
##############################################################
TARGET_USE_INTEL_LIBDRM := true
TARGET_USE_INTEL_GRALLOC := false
TARGET_USE_INTEL_HWCOMPOSER := true
TARGET_USE_GRALLOC_VHAL     := false
TARGET_USE_HWCOMPOSER_VHAL  := true

LIBDRM_VER ?= intel

BOARD_MESA3D_USES_MESON_BUILD := true
BOARD_MESA3D_GALLIUM_DRIVERS := iris
BOARD_MESA3D_VULKAN_DRIVERS := intel
BOARD_MESA3D_BUILD_LIBDRM := true
TARGET_BOARD_PLATFORM := ICS3A

BOARD_USE_MESA := true
BOARD_GPU_DRIVERS := iris
BOARD_USES_MINIGBM := true
INTEL_MINIGBM := vendor/intel/external/project-celadon/minigbm
BOARD_USES_GRALLOC1 := true

BOARD_USE_CUSTOMIZED_MESA := true

VSYNC_EVENT_PHASE_OFFSET_NS := 7000000
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 1000000
##############################################################
# Source: device/intel/mixins/groups/houdini/true/BoardConfig.mk
##############################################################
# Install Native Bridge
WITH_NATIVE_BRIDGE := true

# Enable ARM codegen for x86 with Native Bridge
BUILD_ARM_FOR_X86 := true

# Native Bridge ABI List
NB_ABI_LIST_32_BIT := armeabi-v7a armeabi
NB_ABI_LIST_64_BIT := arm64-v8a

# Support 64 Bit Apps
TARGET_CPU_ABI_LIST_64_BIT ?= $(TARGET_CPU_ABI) $(TARGET_CPU_ABI2)
TARGET_CPU_ABI_LIST_32_BIT ?= $(TARGET_2ND_CPU_ABI) $(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := \
    $(TARGET_CPU_ABI_LIST_64_BIT) \
    $(TARGET_CPU_ABI_LIST_32_BIT) \
    $(NB_ABI_LIST_64_BIT) \
    $(NB_ABI_LIST_32_BIT)
TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
TARGET_CPU_ABI_LIST_64_BIT += $(NB_ABI_LIST_64_BIT)
##############################################################
# Source: device/intel/mixins/groups/media/true/BoardConfig.mk
##############################################################
INTEL_STAGEFRIGHT := true
USE_MEDIASDK := true
BOARD_HAVE_MEDIASDK_OPEN_SOURCE := true
ENABLE_MAX_NUM_REORDER_FRAMES_OUTPUT := false
BOARD_HAVE_OMX_SRC := true

# OneVPL integration
USE_ONEVPL := true

BUILD_BROKEN_USES_BUILD_HOST_STATIC_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_SHARED_LIBRARY := true
BUILD_BROKEN_USES_BUILD_HOST_EXECUTABLE := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
# ------------------ END MIX-IN DEFINITIONS ------------------
