#!/bin/sh

unamestr=`uname`
if [ "$unamestr" = "Linux" -o "$unamestr" = "linux" ]; then

  if [ -f $ANDROID_BUILD_TOP/vendor/intel/utils/cap_checker.py ]; then
    python $ANDROID_BUILD_TOP/vendor/intel/utils/cap_checker.py "$@"
  else
    echo "$ANDROID_BUILD_TOP/vendor/intel/utils/cap_checker.py not found, skipping check..."
  fi
else
  echo "sesearch is only supported on linux"
fi
